# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zaawansowane Metody i Techniki Analizy Danych
email: roman.bartusiak@pwr.edu.pl
description: Zaawansowane Metody i Techniki Analizy Danych
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zmitad.github.io" # the base hostname & protocol for your site
github_username:  riomus

# Gems
gems: 
- jekyll-archives
- jekyll-paginate

# Config
paginate: 5
paginate_path: "page/:num"
# Build settings
markdown: kramdown

# Archive
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
